site_name: support.avm99963.com
site_url: https://support.avm99963.com/
site_author: Adrià Vilanova Martínez (@avm99963)
theme:
  name: 'material'
  language: 'es'
  icon:
    logo: material/help-box
  custom_dir: overrides
repo_name: avm99963/support.avm99963.com
repo_url: https://github.com/avm99963/support.avm99963.com
extra_css: ["css/styles.css"]
plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.footnotes
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.details
  - meta
nav:
  - 'Sobre esta web': 'index.md'
  - 'Chrome':
    - 'Malware en Chrome': 'chrome/malware.md'
    - 'Inhabilitar extensiones de Chrome': 'chrome/diagnostico-extensiones.md'
    - 'Chrome no carga páginas web': 'chrome/no-carga-paginas-web.md'
    - 'Canales de Chrome': 'chrome/canales.md'
    - 'Error con certificado': 'chrome/error-certificado.md'
    - 'Volver a mostrar flags antiguas': 'chrome/mostrar-flags-antiguas.md'
    - 'Solucionar problemas con las imágenes de fondo de Meet': 'chrome/fondo-meet.md'
    - 'Traducciones':
      - 'Descarte y recarga de pestañas': 'chrome/traducciones/descarte-recarga-pestanas.md'
      - 'Ataques locales en Chrome': 'chrome/traducciones/ataques-locales-chrome.md'
    - 'Para desarrolladores':
      - 'Hacer una bisección de Chrome': 'chrome/desarrolladores/biseccion.md'
      - 'Vida de un objeto URLRequest': 'chrome/desarrolladores/vida-de-una-url-request.md'
      - 'Un curso rápido sobre diagnóstico de problemas con chrome://net-internals': 'chrome/desarrolladores/curso-diagnostico-net-internals.md'
  - 'Gmail':
    - 'Cambiar el idioma de Gmail': 'gmail/cambiar-idioma.md'
  - 'Miscelánea':
    - 'Cómo insertar una captura de pantalla en los Foros de Google': 'misc/captura-pantalla-foros-google.md'
extra:
  social:
    - icon: material/web
      link: https://avm99963.com
    - icon: fontawesome/brands/github
      link: https://github.com/avm99963
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/avm99963
copyright: Copyright &copy; Adrià Vilanova Martínez. Except as otherwise noted, the content of this page is licensed under the <a href="https://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 License</a>.
